sudo: false

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

env:
  global:
  - secure: "RXbWkpN3Ks+Egp4swZFL20jaruEkXrk2+tNoaTXSn7SY7BW8nlsBFfy7gFiVr/Uz5WP7VT25EwVbPqLbnYoW1dR6Ql6wE9uv+EI8bIwjSfGp2Qtmh1/KXA3EL3yVWiYrxqEyMYXioVXQXXRGSC+8lK+ve1yW4YVEjUhB4s9mB/E="

install: ./gradlew -q clean assemble

script: ./gradlew -q check publishGhPages
